#!/usr/bin/env python3
"""Validate threshold masks and print foreground statistics as JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np


def _load_npy(filepath: str) -> tuple[Path, np.ndarray]:
    path = Path(filepath).expanduser().resolve()
    if path.suffix.lower() != ".npy":
        raise ValueError(f"Expected a .npy file: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"File does not exist: {path}")
    return path, np.load(path, mmap_mode="r", allow_pickle=False)


def _parse_mask(specification: str) -> tuple[str, str]:
    if "=" not in specification:
        raise ValueError(
            f"Mask must use THRESHOLD=PATH syntax: {specification!r}"
        )
    threshold, filepath = specification.split("=", 1)
    if not threshold.strip() or not filepath.strip():
        raise ValueError(
            f"Mask must use THRESHOLD=PATH syntax: {specification!r}"
        )
    return threshold.strip(), filepath.strip()


def compare(raw_filepath: str, mask_specs: list[str]) -> dict[str, Any]:
    raw_path, raw = _load_npy(raw_filepath)
    if raw.ndim != 3:
        raise ValueError(f"Raw CT array must be 3D, found shape {raw.shape}")

    candidates = []
    for specification in mask_specs:
        threshold_label, mask_filepath = _parse_mask(specification)
        mask_path, mask = _load_npy(mask_filepath)
        if mask.shape != raw.shape:
            raise ValueError(
                f"Mask shape {mask.shape} does not match raw shape {raw.shape}: "
                f"{mask_path}"
            )
        if mask.dtype.kind not in "bui":
            raise TypeError(
                f"Mask must use a boolean or integer dtype, found {mask.dtype}: "
                f"{mask_path}"
            )

        foreground = int(np.count_nonzero(mask))
        total = int(mask.size)
        candidates.append(
            {
                "threshold": threshold_label,
                "path": str(mask_path),
                "dtype": str(mask.dtype),
                "foreground_voxels": foreground,
                "total_voxels": total,
                "foreground_percent": (100.0 * foreground / total) if total else 0.0,
            }
        )

    return {
        "raw_path": str(raw_path),
        "shape": list(raw.shape),
        "candidates": candidates,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compare binary masks generated by a CT threshold sweep."
    )
    parser.add_argument("--raw", required=True, help="Path to the raw 3D CT .npy")
    parser.add_argument(
        "--mask",
        action="append",
        required=True,
        metavar="THRESHOLD=PATH",
        help="Candidate threshold and mask path; repeat for each candidate",
    )
    args = parser.parse_args()

    try:
        result = compare(args.raw, args.mask)
    except (OSError, TypeError, ValueError) as exc:
        parser.exit(1, f"error: {exc}\n")

    print(json.dumps(result, indent=2, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
